#!/bin/bash

#$ -P short
#$ -o /dev/null
#$ -e /dev/null

export PATH="$PATH:/lfs/l3/gerda/pertoldi/swmod-bin/bat/linux-scientific-7.3-x86_64/master/bin:/lfs/l2/gerda/pertoldi/swmod-bin/root/linux-scientific-7.3-x86_64/6.12.06/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lfs/l3/gerda/pertoldi/swmod-bin/bat/linux-scientific-7.3-x86_64/master/lib:/lfs/l2/gerda/pertoldi/swmod-bin/root/linux-scientific-7.3-x86_64/6.12.06/lib"

REPO=/lfs/l2/gerda/pertoldi/0nbb-sensitivity

export OMP_NUM_THREADS=1
cd $REPO
bin/discSensVsBI masterconf.json $1 &> tools/qsub/log/0nbb-sensitivity.$1.log

# send me email if last job
if [[ $(qstat | grep 'znbb' | wc -l) -eq 1 ]]; then
    echo '0nbb-sensitivity jobs complete!' | mail -s '[lfs2-mpi-hd-mpg.de] Status Report' pertoldi@pd.infn.it
fi
