#!/bin/bash

#$ -P short
#$ -o /dev/null
#$ -e /dev/null

export PATH="$PATH:/lfs/l3/gerda/pertoldi/swmod-bin/bat/linux-scientific-7.3-x86_64/master/bin:/lfs/l2/gerda/pertoldi/swmod-bin/root/linux-scientific-7.3-x86_64/6.12.06/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lfs/l3/gerda/pertoldi/swmod-bin/bat/linux-scientific-7.3-x86_64/master/lib:/lfs/l2/gerda/pertoldi/swmod-bin/root/linux-scientific-7.3-x86_64/6.12.06/lib"

REPO=/lfs/l2/gerda/pertoldi/0nbb-sensitivity

$REPO/bin/discSensVsBI $REPO/masterconf.json $1 &> $REPO/tools/qsub/log/0nbb-sensitivity.$1.log

# send me email if last job
if [[ `qstat -r | grep znbb-sensitivity | grep "Full jobname:"` ]]; then
    echo "[lfs2-mpi-hd-mpg.de] 0nbb-sensitivity jobs complete!" | sendmail -v pertoldi@pd.infn.it
fi
